export const routePath = {
  dashboard: "/dashboard",
  transactions: "/transactions",
  transferself: "/transferself",
  transferother: "/transferother",
  transfersterling: "/transfersterling",
  airtime: "/airtime",
  airtimeothers: "/airtimeothers",
  investments: "/investments",
  login: "/login",
  signup: "/signup",
  otp: "/otp",
  forgotPassword: "/forgot-password",
  home: "/",
};
